### ISSUE TITLE
Support 7.20

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/polyflow-examples#233]
Switch examples to latest Camunda Spring Boo, JDK 17..

## Steps

- [x] JDK 17
- [x] Spring Boot 3.1.3
- [x] Camunda 7.20
- [x] Camunda 7.20 SQL Scripts
- [x] Polyflow 4.0.0 (4.0.0-SNAPSHOT)
- [x] Camunda BPM Data 1.4.0
- [x] Camunda Platform 7 Mockito 7.20.0
- [x] Axon Server Connector 4.8.2 // FIXME, do we need it?
- [x] SQL sequence per table
- [x] SQL dialect pimping
- [x] OpenAPI genarator (`useSpringBoot3`)

**Comment by lbilger** [comment]
My notes for process engine migration to Camunda 7.20 / Polyflow 4 etc. - some notes are specific to our setup (e.g. Azure SQL database), but maybe it helps:

* Update versions in your POM according to the changes above
* Do the javax -> jakarta migration
* If you have a dependency on org.apache.httpcomponents:httpclient, use org.apache.httpcomponents.client5:httpclient5 instead
* If you have a dependency on groovy, change the group id from org.codehaus.groovy to org.apache.groovy
* If you are using the OpenAPI Generator, depending on which generator you use, you might have to set the config options `useSpringBoot3` or `useJakartaEe` to `true`
* Either migrate your database schema to use `DATETIMEOFFSET` instead of `DATETIME2` for `Instant`s or set `spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type` to 
  `TIMESTAMP` in your `application.yaml`.
* Either migrate your database schema to use `UNIQUEIDENTIFIER` instead of `BINARY` for `UUID`s or set `spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type` to `BINARY` 
  in your `application.yaml`.
* Due to a change in how Hibernate handles sequences, you will either need to replace the `hibernate_sequence` with per-table sequences (recommended) or set the JPA property
  `hibernate.id.db_structure_naming_strategy` to `legacy` to restore the old behavior. An example database script for creating the sequences can be found is attached below
```SQL
DECLARE @next_value BIGINT, @sql NVARCHAR(MAX);
SET @next_value = NEXT VALUE FOR hibernate_sequence;
SET @sql = 'CREATE SEQUENCE association_value_entry_seq START WITH ' + CAST(@next_value AS NVARCHAR) + ' INCREMENT BY 50'
EXEC (@sql)
SET @sql = 'CREATE SEQUENCE domain_event_entry_seq START WITH ' + CAST(@next_value AS NVARCHAR) + ' INCREMENT BY 50'
EXEC (@sql)
DROP SEQUENCE hibernate_sequence;
```
* The database schema upgrade from 7.19 to 7.20 is not very spectacular, but you should apply it nonetheless. Add the scripts to your Flyway migrations directory or whatever you use.
